### ISSUE TITLE
Category conversion

### ISSUE THREAD

**Issue by Drmzindec** [voceconnect/post-type-converter#13]
It would be nice to keep the categories when converting custom post types.

Ex.
I have a custom post type called, Articles which functions as posts (Huge fail from former dev), i would like to convert all of the Articles to Posts so that i can utilize the functionality a lot better and easier.

So essentially i would like to convert Articles to Posts and withhold their categories and the hierarchy.

**Comment by prettyboymp** [comment]
If the original post type that you are converting from is using the built in categories taxonomy, the plugin should already be doing this.  Does your Articles post type uses the built in Categories taxonomy?  Or is it a custom taxonomy?

**Comment by Drmzindec** [comment]
It uses a custom taxonomy, i am converting the categories in mysql to the built in Categories type to test if that will work.
