### ISSUE TITLE
Can we set for editors?

### ISSUE THREAD

**Issue by davidperezgar** [voceconnect/post-type-converter#14]
I'd like to share it this metabox for editor. Is it working?

**Comment by saralomoutinho** [comment]
Hi there!

I have the same query as above - please advise how I can allow other user roles access to the tool.

Thanks!

**Comment by kevinlangleyjr** [comment]
You can filter the value here to instead choose a capability that editors have instead.

https://github.com/voceconnect/post-type-converter/blob/master/post-type-converter.php#L16
